"""empty message

Revision ID: 0f0efa4837f9
Revises: 81487331f149
Create Date: 2019-03-18 21:52:02.231777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0efa4837f9'
down_revision = '81487331f149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    #op.drop_column('user', 'last_senn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_senn', sa.DATETIME(), nullable=True))
    op.drop_table('followers')
    # ### end Alembic commands ###
