"""new fields in user model corrected

Revision ID: 1bd8cdbe6848
Revises: 662144de9041
Create Date: 2019-02-21 21:02:50.110327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd8cdbe6848'
down_revision = '662144de9041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_senn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_senn', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
