"""new fields in user model

Revision ID: 662144de9041
Revises: 7157599ae9b6
Create Date: 2019-02-21 21:02:22.466617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662144de9041'
down_revision = '7157599ae9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_senn', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_senn')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
