"""add language to posts

Revision ID: 81487331f149
Revises: 1bd8cdbe6848
Create Date: 2019-03-18 17:47:57.613491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81487331f149'
down_revision = '1bd8cdbe6848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
